/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ProtectedLeaderboardRouteImport } from './routes/_protected/leaderboard'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedTeamsIndexRouteImport } from './routes/_protected/teams/index'
import { Route as ProtectedProjectsIndexRouteImport } from './routes/_protected/projects/index'
import { Route as ProtectedJudgingIndexRouteImport } from './routes/_protected/judging/index'
import { Route as ProtectedHackathonsIndexRouteImport } from './routes/_protected/hackathons/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedTeamsTeamIdRouteImport } from './routes/_protected/teams/$teamId'
import { Route as ProtectedProjectsProjectIdRouteImport } from './routes/_protected/projects/$projectId'
import { Route as ProtectedOrganizerJudgesRouteImport } from './routes/_protected/organizer/judges'
import { Route as ProtectedOrganizerExportsRouteImport } from './routes/_protected/organizer/exports'
import { Route as ProtectedHackathonsHackathonIdRouteImport } from './routes/_protected/hackathons/$hackathonId'
import { Route as ProtectedDashboardProjectsRouteImport } from './routes/_protected/dashboard/projects'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedAdminTeamsRouteImport } from './routes/_protected/admin/teams'
import { Route as ProtectedAdminProjectsRouteImport } from './routes/_protected/admin/projects'
import { Route as ProtectedAdminLeaderboardRouteImport } from './routes/_protected/admin/leaderboard'
import { Route as ProtectedAdminJudgesRouteImport } from './routes/_protected/admin/judges'
import { Route as ProtectedAdminHackathonsRouteImport } from './routes/_protected/admin/hackathons'
import { Route as ProtectedAdminConfigRouteImport } from './routes/_protected/admin/config'
import { Route as ProtectedOrganizerHackathonsIndexRouteImport } from './routes/_protected/organizer/hackathons/index'
import { Route as ProtectedOrganizerHackathonsCreateRouteImport } from './routes/_protected/organizer/hackathons/create'
import { Route as ProtectedOrganizerHackathonsHackathonIdRouteImport } from './routes/_protected/organizer/hackathons/$hackathonId'

const IndexLazyRouteImport = createFileRoute('/')()

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLeaderboardRoute = ProtectedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamsIndexRoute = ProtectedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProjectsIndexRoute = ProtectedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJudgingIndexRoute = ProtectedJudgingIndexRouteImport.update({
  id: '/judging/',
  path: '/judging/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHackathonsIndexRoute =
  ProtectedHackathonsIndexRouteImport.update({
    id: '/hackathons/',
    path: '/hackathons/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamsTeamIdRoute = ProtectedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProjectsProjectIdRoute =
  ProtectedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizerJudgesRoute =
  ProtectedOrganizerJudgesRouteImport.update({
    id: '/organizer/judges',
    path: '/organizer/judges',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizerExportsRoute =
  ProtectedOrganizerExportsRouteImport.update({
    id: '/organizer/exports',
    path: '/organizer/exports',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedHackathonsHackathonIdRoute =
  ProtectedHackathonsHackathonIdRouteImport.update({
    id: '/hackathons/$hackathonId',
    path: '/hackathons/$hackathonId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardProjectsRoute =
  ProtectedDashboardProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminTeamsRoute = ProtectedAdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminProjectsRoute = ProtectedAdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminLeaderboardRoute =
  ProtectedAdminLeaderboardRouteImport.update({
    id: '/admin/leaderboard',
    path: '/admin/leaderboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminJudgesRoute = ProtectedAdminJudgesRouteImport.update({
  id: '/admin/judges',
  path: '/admin/judges',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminHackathonsRoute =
  ProtectedAdminHackathonsRouteImport.update({
    id: '/admin/hackathons',
    path: '/admin/hackathons',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminConfigRoute = ProtectedAdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizerHackathonsIndexRoute =
  ProtectedOrganizerHackathonsIndexRouteImport.update({
    id: '/organizer/hackathons/',
    path: '/organizer/hackathons/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizerHackathonsCreateRoute =
  ProtectedOrganizerHackathonsCreateRouteImport.update({
    id: '/organizer/hackathons/create',
    path: '/organizer/hackathons/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizerHackathonsHackathonIdRoute =
  ProtectedOrganizerHackathonsHackathonIdRouteImport.update({
    id: '/organizer/hackathons/$hackathonId',
    path: '/organizer/hackathons/$hackathonId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/leaderboard': typeof ProtectedLeaderboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/config': typeof ProtectedAdminConfigRoute
  '/admin/hackathons': typeof ProtectedAdminHackathonsRoute
  '/admin/judges': typeof ProtectedAdminJudgesRoute
  '/admin/leaderboard': typeof ProtectedAdminLeaderboardRoute
  '/admin/projects': typeof ProtectedAdminProjectsRoute
  '/admin/teams': typeof ProtectedAdminTeamsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/dashboard/projects': typeof ProtectedDashboardProjectsRoute
  '/hackathons/$hackathonId': typeof ProtectedHackathonsHackathonIdRoute
  '/organizer/exports': typeof ProtectedOrganizerExportsRoute
  '/organizer/judges': typeof ProtectedOrganizerJudgesRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/hackathons/': typeof ProtectedHackathonsIndexRoute
  '/judging/': typeof ProtectedJudgingIndexRoute
  '/projects/': typeof ProtectedProjectsIndexRoute
  '/teams/': typeof ProtectedTeamsIndexRoute
  '/organizer/hackathons/$hackathonId': typeof ProtectedOrganizerHackathonsHackathonIdRoute
  '/organizer/hackathons/create': typeof ProtectedOrganizerHackathonsCreateRoute
  '/organizer/hackathons/': typeof ProtectedOrganizerHackathonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/leaderboard': typeof ProtectedLeaderboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/config': typeof ProtectedAdminConfigRoute
  '/admin/hackathons': typeof ProtectedAdminHackathonsRoute
  '/admin/judges': typeof ProtectedAdminJudgesRoute
  '/admin/leaderboard': typeof ProtectedAdminLeaderboardRoute
  '/admin/projects': typeof ProtectedAdminProjectsRoute
  '/admin/teams': typeof ProtectedAdminTeamsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/dashboard/projects': typeof ProtectedDashboardProjectsRoute
  '/hackathons/$hackathonId': typeof ProtectedHackathonsHackathonIdRoute
  '/organizer/exports': typeof ProtectedOrganizerExportsRoute
  '/organizer/judges': typeof ProtectedOrganizerJudgesRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/hackathons': typeof ProtectedHackathonsIndexRoute
  '/judging': typeof ProtectedJudgingIndexRoute
  '/projects': typeof ProtectedProjectsIndexRoute
  '/teams': typeof ProtectedTeamsIndexRoute
  '/organizer/hackathons/$hackathonId': typeof ProtectedOrganizerHackathonsHackathonIdRoute
  '/organizer/hackathons/create': typeof ProtectedOrganizerHackathonsCreateRoute
  '/organizer/hackathons': typeof ProtectedOrganizerHackathonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/leaderboard': typeof ProtectedLeaderboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_protected/admin/config': typeof ProtectedAdminConfigRoute
  '/_protected/admin/hackathons': typeof ProtectedAdminHackathonsRoute
  '/_protected/admin/judges': typeof ProtectedAdminJudgesRoute
  '/_protected/admin/leaderboard': typeof ProtectedAdminLeaderboardRoute
  '/_protected/admin/projects': typeof ProtectedAdminProjectsRoute
  '/_protected/admin/teams': typeof ProtectedAdminTeamsRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
  '/_protected/dashboard/projects': typeof ProtectedDashboardProjectsRoute
  '/_protected/hackathons/$hackathonId': typeof ProtectedHackathonsHackathonIdRoute
  '/_protected/organizer/exports': typeof ProtectedOrganizerExportsRoute
  '/_protected/organizer/judges': typeof ProtectedOrganizerJudgesRoute
  '/_protected/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
  '/_protected/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/hackathons/': typeof ProtectedHackathonsIndexRoute
  '/_protected/judging/': typeof ProtectedJudgingIndexRoute
  '/_protected/projects/': typeof ProtectedProjectsIndexRoute
  '/_protected/teams/': typeof ProtectedTeamsIndexRoute
  '/_protected/organizer/hackathons/$hackathonId': typeof ProtectedOrganizerHackathonsHackathonIdRoute
  '/_protected/organizer/hackathons/create': typeof ProtectedOrganizerHackathonsCreateRoute
  '/_protected/organizer/hackathons/': typeof ProtectedOrganizerHackathonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/leaderboard'
    | '/invite/$token'
    | '/admin/config'
    | '/admin/hackathons'
    | '/admin/judges'
    | '/admin/leaderboard'
    | '/admin/projects'
    | '/admin/teams'
    | '/admin/users'
    | '/dashboard/projects'
    | '/hackathons/$hackathonId'
    | '/organizer/exports'
    | '/organizer/judges'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/admin/'
    | '/hackathons/'
    | '/judging/'
    | '/projects/'
    | '/teams/'
    | '/organizer/hackathons/$hackathonId'
    | '/organizer/hackathons/create'
    | '/organizer/hackathons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/leaderboard'
    | '/invite/$token'
    | '/admin/config'
    | '/admin/hackathons'
    | '/admin/judges'
    | '/admin/leaderboard'
    | '/admin/projects'
    | '/admin/teams'
    | '/admin/users'
    | '/dashboard/projects'
    | '/hackathons/$hackathonId'
    | '/organizer/exports'
    | '/organizer/judges'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/admin'
    | '/hackathons'
    | '/judging'
    | '/projects'
    | '/teams'
    | '/organizer/hackathons/$hackathonId'
    | '/organizer/hackathons/create'
    | '/organizer/hackathons'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/register'
    | '/_protected/dashboard'
    | '/_protected/leaderboard'
    | '/invite/$token'
    | '/_protected/admin/config'
    | '/_protected/admin/hackathons'
    | '/_protected/admin/judges'
    | '/_protected/admin/leaderboard'
    | '/_protected/admin/projects'
    | '/_protected/admin/teams'
    | '/_protected/admin/users'
    | '/_protected/dashboard/projects'
    | '/_protected/hackathons/$hackathonId'
    | '/_protected/organizer/exports'
    | '/_protected/organizer/judges'
    | '/_protected/projects/$projectId'
    | '/_protected/teams/$teamId'
    | '/_protected/admin/'
    | '/_protected/hackathons/'
    | '/_protected/judging/'
    | '/_protected/projects/'
    | '/_protected/teams/'
    | '/_protected/organizer/hackathons/$hackathonId'
    | '/_protected/organizer/hackathons/create'
    | '/_protected/organizer/hackathons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/leaderboard': {
      id: '/_protected/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof ProtectedLeaderboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teams/': {
      id: '/_protected/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof ProtectedTeamsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/projects/': {
      id: '/_protected/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProtectedProjectsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/judging/': {
      id: '/_protected/judging/'
      path: '/judging'
      fullPath: '/judging/'
      preLoaderRoute: typeof ProtectedJudgingIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hackathons/': {
      id: '/_protected/hackathons/'
      path: '/hackathons'
      fullPath: '/hackathons/'
      preLoaderRoute: typeof ProtectedHackathonsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teams/$teamId': {
      id: '/_protected/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof ProtectedTeamsTeamIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/projects/$projectId': {
      id: '/_protected/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizer/judges': {
      id: '/_protected/organizer/judges'
      path: '/organizer/judges'
      fullPath: '/organizer/judges'
      preLoaderRoute: typeof ProtectedOrganizerJudgesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizer/exports': {
      id: '/_protected/organizer/exports'
      path: '/organizer/exports'
      fullPath: '/organizer/exports'
      preLoaderRoute: typeof ProtectedOrganizerExportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hackathons/$hackathonId': {
      id: '/_protected/hackathons/$hackathonId'
      path: '/hackathons/$hackathonId'
      fullPath: '/hackathons/$hackathonId'
      preLoaderRoute: typeof ProtectedHackathonsHackathonIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/projects': {
      id: '/_protected/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof ProtectedDashboardProjectsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/teams': {
      id: '/_protected/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof ProtectedAdminTeamsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/projects': {
      id: '/_protected/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof ProtectedAdminProjectsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/leaderboard': {
      id: '/_protected/admin/leaderboard'
      path: '/admin/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof ProtectedAdminLeaderboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/judges': {
      id: '/_protected/admin/judges'
      path: '/admin/judges'
      fullPath: '/admin/judges'
      preLoaderRoute: typeof ProtectedAdminJudgesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/hackathons': {
      id: '/_protected/admin/hackathons'
      path: '/admin/hackathons'
      fullPath: '/admin/hackathons'
      preLoaderRoute: typeof ProtectedAdminHackathonsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/config': {
      id: '/_protected/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof ProtectedAdminConfigRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizer/hackathons/': {
      id: '/_protected/organizer/hackathons/'
      path: '/organizer/hackathons'
      fullPath: '/organizer/hackathons/'
      preLoaderRoute: typeof ProtectedOrganizerHackathonsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizer/hackathons/create': {
      id: '/_protected/organizer/hackathons/create'
      path: '/organizer/hackathons/create'
      fullPath: '/organizer/hackathons/create'
      preLoaderRoute: typeof ProtectedOrganizerHackathonsCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizer/hackathons/$hackathonId': {
      id: '/_protected/organizer/hackathons/$hackathonId'
      path: '/organizer/hackathons/$hackathonId'
      fullPath: '/organizer/hackathons/$hackathonId'
      preLoaderRoute: typeof ProtectedOrganizerHackathonsHackathonIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardProjectsRoute: typeof ProtectedDashboardProjectsRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardProjectsRoute: ProtectedDashboardProjectsRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedLeaderboardRoute: typeof ProtectedLeaderboardRoute
  ProtectedAdminConfigRoute: typeof ProtectedAdminConfigRoute
  ProtectedAdminHackathonsRoute: typeof ProtectedAdminHackathonsRoute
  ProtectedAdminJudgesRoute: typeof ProtectedAdminJudgesRoute
  ProtectedAdminLeaderboardRoute: typeof ProtectedAdminLeaderboardRoute
  ProtectedAdminProjectsRoute: typeof ProtectedAdminProjectsRoute
  ProtectedAdminTeamsRoute: typeof ProtectedAdminTeamsRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
  ProtectedHackathonsHackathonIdRoute: typeof ProtectedHackathonsHackathonIdRoute
  ProtectedOrganizerExportsRoute: typeof ProtectedOrganizerExportsRoute
  ProtectedOrganizerJudgesRoute: typeof ProtectedOrganizerJudgesRoute
  ProtectedProjectsProjectIdRoute: typeof ProtectedProjectsProjectIdRoute
  ProtectedTeamsTeamIdRoute: typeof ProtectedTeamsTeamIdRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedHackathonsIndexRoute: typeof ProtectedHackathonsIndexRoute
  ProtectedJudgingIndexRoute: typeof ProtectedJudgingIndexRoute
  ProtectedProjectsIndexRoute: typeof ProtectedProjectsIndexRoute
  ProtectedTeamsIndexRoute: typeof ProtectedTeamsIndexRoute
  ProtectedOrganizerHackathonsHackathonIdRoute: typeof ProtectedOrganizerHackathonsHackathonIdRoute
  ProtectedOrganizerHackathonsCreateRoute: typeof ProtectedOrganizerHackathonsCreateRoute
  ProtectedOrganizerHackathonsIndexRoute: typeof ProtectedOrganizerHackathonsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedLeaderboardRoute: ProtectedLeaderboardRoute,
  ProtectedAdminConfigRoute: ProtectedAdminConfigRoute,
  ProtectedAdminHackathonsRoute: ProtectedAdminHackathonsRoute,
  ProtectedAdminJudgesRoute: ProtectedAdminJudgesRoute,
  ProtectedAdminLeaderboardRoute: ProtectedAdminLeaderboardRoute,
  ProtectedAdminProjectsRoute: ProtectedAdminProjectsRoute,
  ProtectedAdminTeamsRoute: ProtectedAdminTeamsRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
  ProtectedHackathonsHackathonIdRoute: ProtectedHackathonsHackathonIdRoute,
  ProtectedOrganizerExportsRoute: ProtectedOrganizerExportsRoute,
  ProtectedOrganizerJudgesRoute: ProtectedOrganizerJudgesRoute,
  ProtectedProjectsProjectIdRoute: ProtectedProjectsProjectIdRoute,
  ProtectedTeamsTeamIdRoute: ProtectedTeamsTeamIdRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedHackathonsIndexRoute: ProtectedHackathonsIndexRoute,
  ProtectedJudgingIndexRoute: ProtectedJudgingIndexRoute,
  ProtectedProjectsIndexRoute: ProtectedProjectsIndexRoute,
  ProtectedTeamsIndexRoute: ProtectedTeamsIndexRoute,
  ProtectedOrganizerHackathonsHackathonIdRoute:
    ProtectedOrganizerHackathonsHackathonIdRoute,
  ProtectedOrganizerHackathonsCreateRoute:
    ProtectedOrganizerHackathonsCreateRoute,
  ProtectedOrganizerHackathonsIndexRoute:
    ProtectedOrganizerHackathonsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
